env:
  browser: false
  es2021: true
  mocha: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"

